apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 467827689045.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 467827689045.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: 38a21e34
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
